### ISSUE TITLE
Question: is there a test environment/account for this api?

### ISSUE THREAD

**Issue by lzkill** [Biscoint/biscoint-api-node#12]
How can one test the api without live real money on the line?

**Comment by jonathascarrijo** [comment]
Unfortunately we currently do not have a public test environment. It would definitely be very helpful, and we intend to provide one some time in the future.

For now, the best way is to put a small amount of money. The minimum buy is R$50, and the minimum sell is 0.0001 BTC, so probably putting R$100,00 to be lost in "development cost" would be enough.
