### ISSUE TITLE
Question: any plans to allow other assets?

### ISSUE THREAD

**Issue by lzkill** [Biscoint/biscoint-api-node#13]
Do yous guys have any plans to allow ETH or USDT on the trading methods?

**Comment by bolaum** [comment]
ETH is almost there (release in the next few days)! It's already in beta through the user interface. You'll need to be part of the beta to use it though, so ask for it by clicking on ETH in the top left panel of the interface if you aren't already assigned to the beta.

USDT will take a little longer, but it's in our (near future) plans.

**Comment by itxtoledo** [comment]
PR #10 introduces better code documentation with typescript built-in interfaces and allow trade with other assets available in your account

**Comment by itxtoledo** [comment]
You will soon be able to trade other currencies in biscoint. At that time you can trade ETH and BTC, when new currencies are introduced the current version of the biscoint-api-node package will normally support.  Thank you for your interest, I will be closing this issue.
