### ISSUE TITLE
Feature request: proxy config

### ISSUE THREAD

**Issue by lzkill** [Biscoint/biscoint-api-node#14]
Right now it's not possible to config Axios with credentials to a http proxy. That would definitely extend the options one have to deploy trade bots.

**Comment by jonathascarrijo** [comment]
I agree. It would be nice if we could set any configuration allowed by axios. Maybe the presence of an `axios.json` config file could imply overriding the default settings.

**Comment by lzkill** [comment]
From the [Axios docs](https://github.com/axios/axios):

 _You can also define your proxy using the conventional `http_proxy` and `https_proxy` environment variables._

I've tested and it works. Closing here, thank you!
