### ISSUE TITLE
question: searching a currency value by date and time

### ISSUE THREAD

**Issue by YuriFontella** [Biscoint/biscoint-api-node#25]
It's more a question to resolve a question, looking at the documentation I realized that there is no endpoint where I can get a value of a currency passing a date and time as a parameter.

This is not available in the biscoint API, but might this be possible in some other API?

I believe I've looked at more than 10 other services and I don't find this type of query.

**Comment by itxtoledo** [comment]
I think this request is valid but it has no connection with the library for now, so I'm closing it but I passed your request to our team. Contact support and as soon as we add this endpoint we will let you know.
