### ISSUE TITLE
Falha API balance não retorna valor em reais, só bitcoins

### ISSUE THREAD

**Issue by caioaabrantes** [Biscoint/biscoint-api-node#8]
Estou rodando o robô de arbitragem e está dando falha na consulta da API balances:

`  balances = await bc.balance();`
`  const { BRL, BTC } = balances;`
`  handleMessage(`Balances:  BRL: ${BRL} - BTC: ${BTC} - ${JSON.stringify(balances)}`);`

Ele acaba imprimindo esse valor zerado para reais, independentemente do valor de BTC

`2021-07-20T09:22:43.864Z [Biscoint BOT] [info] - Balances:  BRL: 0.00 - BTC: 0.00276863 - {"BRL":"0.00","BTC":"0.00276863"}`

Parece que há algum problema no response da API do lado do servidor que não retorna o valor em reais, só em bitcoins.

**Comment by bolaum** [comment]
Você conferiu seu saldo através da interface web (https://biscoint.io)?

Todos os endpoints estão funcionando normalmente.

**Comment by caioaabrantes** [comment]
Conferi, na web aparece o saldo em reais, mas na via API não está retornando o valor em reais, só em bitcoins na consulta do endpoint balances. Você está conseguindo testar normalmente na hora de chamar o endpoint balances?

**Comment by bolaum** [comment]
Então é melhor vc abrir um ticket no suporte.

**Comment by bolaum** [comment]
@caioaabrantes o robô de arbitragem só chama o endpoint de saldo durante a inicialização. Tente reiniciar o robô para ver o retorno. Aqui está tudo normal.

**Comment by caioaabrantes** [comment]
Ele sempre dá esse problema, eu acabei comentando esse trecho de código pois ele comparava o valor em reais retornado pelo endpoint balances com o valor de amount no config.json. Mas vou abrir um chamado via suporte então. Valeu!!
